tap "nikitabobko/tap"
tap "mediosz/tap"

brew "git"
brew "git-lfs"
brew "gh"
brew "neovim"
brew "tmux"
brew "ripgrep"
brew "fzf"
brew "jq"
brew "coreutils"
brew "stow"
brew "pre-commit"

cask "ghostty"
cask "aerospace"
cask "swipeaerospace"
cask "raycast"
cask "karabiner-elements"
cask "unnaturalscrollwheels"
